jdbc.driver=org.sqlite.JDBC
jdbc.url=jdbc:sqlite:ipartex.db
jdbc.user=
jdbc.pass=

jdbc.helper=bibliotecas.accesodatos.JdbcHelperImpl

dao.mensaje=com.ipartex.accesodatos.sqlite.DaoMensajeSqlite
# dao.mensaje=com.ipartex.accesodatos.arraylist.DaoMensajeArrayList
# dao.mensaje=com.ipartex.accesodatos.arraylist.DaoMensajeArrayListMejorada
# dao.mensaje=com.ipartex.accesodatos.map.DaoMensajeTreeMap

# CAMBIO INTRODUCIDO EN ESTE FICHERO
