spring.application.name=uberitspring

spring.datasource.url=jdbc:mysql://localhost:3306/uberitspring
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.data.rest.base-path=/api/v1

spring.mvc.problemdetails.enabled=true
