jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/ipartube
jdbc.user=ipartube_app
jdbc.pass=ipartube

dao.video=com.ipartube.accesodatos.jpa.VideoCrud
dao.comentario=com.ipartube.accesodatos.jpa.ComentarioCrud

negocio.anonimo=com.ipartube.logicanegocio.AnonimoNegocioImpl